---
title: "Lista 1: Probabilidade e variáveis aleatórias"
author: "Leo Bastos"
format: pdf
---

Lista de exercícios da disciplina MD21 - Introdução à Estatística.

1.  Lançaremos uma moeda honesta até obtermos exatamente duas coroas.

    a.  Descreva o espaço amostral.

    b.  Qual a probabilidade de que sejam necessários exatamente $k$ lançamentos?

2.  Suponha que 20% dos proprietários de computador usam computadores da Apple (ex. Macbook), 70% usam computadores da Microsoft e 10% usam diferentes variações do Linux. Suponha também que 65% dos usuários Mac já foram infectados por um vírus de computador, 85% dos usuários de windows e 20% dos usuários Linux já pegaram vírus.

    a.  Qual a probabilidade de selecionarmos um proprietário de computador que já teve o computador infectado por um vírus?

    b.  Dado que ela já teve o computador infectado, qual a probabilidade dela ser um usuário Windows?

3.  Seja a seguinte função de densidade e probabilidade: $$f_X(x) = \left\{ \begin{array}{lc} cx^2 & -1 < x < 1, \\ 0 & \mbox{caso contrário.}\end{array}\right.$$ onde $c$ é uma constante.

    a.  Encontre $c$.

    b.  Encontre a função de probabilidade acumulada de $X$, $F_X(x)$.

    c.  Encontre a função quantil e calcule a mediana de $X$.

4.  Mostre que $$f_X(x) = \theta (1-\theta)^{x-1}, \qquad \theta\in (0,1), \, x=1,2,3,\ldots$$ é uma função de probabilidade.

5.  Seja $X$ uma variável aleatória função de densidade dada por $$f_X(x) = = \left\{ \begin{array}{lc} \frac{\alpha}{x^{\alpha+1}} & x \geq 1, \\ 0 & x<1.\end{array}\right.$$ Encontre a distribuição de $Y = \log(X)$.

6.  Sejam $X$ e $Y$ duas variáveis aleatórias independentes com distribuição uniforme no intervalo $(0,a)$. Encontre $f_Z(z)$ quando

    a.  $Z=X+Y$
    b.  $Z = XY$
    c.  $Z = \max(X,Y)$

7.  Suponha que $X|Y \sim Poisson(Y)$ e $Y \sim Gamma(a,b)$.

    a.  Encontre a distribuição marginal de $X$, $f_X(x)$

    b.  Encontre a distribuição condicional de $Y|X$, $f_{Y|X}(y|x)$
