---
title: "Lista 2: Valor esperado, desigualdades"
author: "Data esperada: 30/4"
format: pdf
---

Segunda lista de exercícios da disciplina MD21 - Introdução à Estatística.

1.  Calcule o valor esperado e variância das seguintes distribuições:
    a.  $X \sim Poisson(\theta)$, $p_X(x) = \theta^x e^{-\theta} / x!, \, x=0,1,2,\ldots$
    b.  $X \sim Beta(a, b)$, $f_X(x) = \Gamma(a+b)/(\Gamma(a)\Gamma(b))x^{a-1}(1-x)^{b-1}, \, x \in (0,1).$
    c. $X \sim \chi^2_n$, $f_X(x) = \frac{1}{2^{n/2}\Gamma(n/2)}x^{n/2-1}e^{-x/2}, \, x>0.$
    
2.  Seja $X \sim Gamma(\alpha, \beta)$ e $Y = 1/X$. Calcule a esperança de $X$ e de $Y$.

3. Seja $X \sim Poisson(\lambda)$ e $Y\sim Poisson(\theta)$, encontre a distribuição de $X+Y$

4. Mostre que $\mathbb{V}[X-Y] = \mathbb{V}[X] + \mathbb{V}[Y] - 2 \mathbb{Cov}(X,Y)$

5. Calcule a função geradora de momentos das distribuiições da questão (1).

6. O coeficiente de assimetria de uma distribuição é definido por
$$\gamma_1 = \mathbb{E}\left[\left( \frac{X-\mu}{\sigma} \right)^3 \right]$$
onde $\mu$ é a média e $\sigma^2$ a variância de $X$. Se $\gamma=0$ dizemos que a distribuição de $X$ é simétrica, se for $\gamma < 0$ a distribuição é simétrica à esquerda, e $\gamma > 0$ simétrica é direita. Encontre o coeficiente de assimetria para as ditribuições da questão (1)

7. Sejam $X$ e $Y$ variáveis aleatórias com função de densidade conjunta 
$$f_{X,Y}(x,y) = e^{-y}, \; 0 \leq x \leq y$$
    a. Encontre as marginais de $X$ e $Y$
    b. Calcule $\mathbb{E}[X]$, $\mathbb{E}[Y]$ e $\mathbb{E}[XY]$
    c. Calcule $\mathbb{V}[X]$, $\mathbb{V}[Y]$ e $\mathbb{Cov}(X,Y)$
    d. Calcule a correlação de  $X$ e $Y$, $\rho_{X,Y}$
  
8. Suponha que $X \sim \chi^2_n$ e $Y \sim \chi^2_m$
    a. Encontre a função geradora de momentos de $X$
    b. Mostre que $X+Y$ segue uma distribuição $\chi^2_{n+m}$
    c Encontre a distribuição de $X / (X+Y)$

9. Seja $X_1,X_2,\ldots,X_n$ variáveis aleatórias independentes de uma distribuição $F$. Seja $Y = \sum_i I(X \leq x) / n$, encontre esperança e variancia de $Y$. E usando a desigualdade de Chebyshev, encontre um limite superior para $\mathbb{P}(|Y - \mathbb{E}[Y]|>\epsilon)$.

10. A desigualdade de Hoeffding diz que para $W_1,W_2,\ldots,W_n$ v.a.s independentes tais que $\mathbb{E}[W_i]=0$ e $a_i<Y_i<b_i$, para $\epsilon > 0$. Para $t>0$
$$\mathbb{P}\left( \sum_{i=1}^n W_i \geq \epsilon \right) \leq e^{-t\epsilon} \prod_{i=1}^n e^{t^2(b_i-a_i)^2/8}$$
Aplique a desigualdade de Hoeffding no exercício anterior (9) para encontrar um limite superior para $\mathbb{P}(|Y - \mathbb{Y}|>\epsilon)$ e compare os valores encontrados.