---
title: "MD21 Introdução à Estatística"
subtitle: ""
author: "Leo Bastos"
format: 
  revealjs:
    logo: ../impa-tech-h.png
    footer: '<https://github.com/lsbastos/md21/>'
    theme: simple
    chalkboard: true
editor: visual
---

## Quem sou eu?

-   Estatístico (graduação, mestrado e doutorado)

-   Pesquisador da Fiocruz e recentemente professor do IMPA tech

-   Trabalho com desenvolvimento e aplicação de métodos estatísticos na epidemiologia das doenças infecciosas

-   Coordeno os sistemas de alerta de epidemias: InfoDengue e InfoGripe

-   Site pessoal: [lsbastos.github.io](https://lsbastos.github.io)

## Burocracias

-   Aulas teoricas: segundas e quartas (1:30-3pm)

-   Aulas práticas: segundas e quartas (8:30-10am).

    -   O curso tem 2 professores auxiliares

-   Avaliação: AV1 e AV2 60% por provas e 40% listas para entregar.

-   Toda aula terá recomendação de exercícios, cada tópico terá uma lista.

-   Slides, exercícios e listas estarão disponíveis no github do curso

## Bibliografia básica

-   RICE, J. A. Mathematical statistics and data analysis. 2006.

-   WASSERMAN, L. All of Statistics. NY, 2004.

-   CASELLA, G.; BERGER, R. L. Statistical inference. 2021.

## Ementa proposta para o curso

1.  Fundamentos (AV1)

    -   Variáveis aleatórias e principais distribuições

    -   Conceitos e procedimentos estatísticos modernos

. . .

2.  Inferência (AV2)

    -   Estimação pontual e intervalar

    -   Bootstrap

    -   Métodos bayesianos

    -   Teoria da decisão

## Introdução à probabilidade

-   Axiomas de probabilidade

-   Independência

-   Probabilidade condicional

-   Teorema de Bayes

## Axiomas de probabilidade

A função $\mathbb{P}$ que atribui um valor real $\mathbb{P}(A)$ para cada evento $A$ é uma função de probabilidade se ela satifaz:

::: incremental
1.  $\mathbb{P}(A) \geq 0$ para todo $A$
2.  $\mathbb{P}(\Omega) = 1$
3.  se $A_1, A_2,\ldots$ são disjuntos, então $$\mathbb{P}\left(\bigcup_{i=1}^{\infty}A_i\right) = \sum_{i=1}^{\infty}\mathbb{P}(A_i)$$
:::

## Independência de eventos

Dizemos que dois eventos $A$ e $B$ são independentes, $A \perp B$, se $$\mathbb{P}(AB) = \mathbb{P}(A \cap B) = \mathbb{P}(A)\mathbb{P}(B)$$

. . .

Dizemos que um conjunto de eventos $\{A_i : i \in I\}$ é independente se $$\mathbb{P}\left(\bigcap_{i \in I} A_i\right) = \prod_{i \in I} \mathbb{P}(A_i)$$

## Probabilidade condicional

Assumindo que $\mathbb{P}(B) > 0$, definimos a probabilidade condicional de $A$ dado a ocorrência de $B$ como $$\mathbb{P}(A \mid B) = \frac{\mathbb{P}(AB)}{\mathbb{P}(B)}.$$

. . .

Lema: Se $A \perp B$, então $\mathbb{P}(A \mid B) = \mathbb{P}(A)$

## Exemplo

Suponha que um teste laboratorial para uma doença $D$ tenha os seguintes resultados $+$ e $-$, com probabilidades:

|     |  $D$  | $D^C$ |
|:---:|:-----:|:-----:|
| $+$ | 0.009 | 0.099 |
| $-$ | 0.001 | 0.891 |

Qual o valor de $\mathbb{P}(D)$ e $\mathbb{P}(+|D)$?

. . .

$$\mathbb{P}(D) = \mathbb{P}(D \cap +) + \mathbb{P}(D \cap -) = {0.009+0.001} = 0.01$$

. . .

$$\mathbb{P}(+|D) = \frac{\mathbb{P}(+ \cap D)}{\mathbb{P}(D)} = \frac{0.009}{0.009+0.001} = 0.9$$

## Teorema de Bayes

Teorema da probabilidade total: Seja $A_1, A_2,\ldots,A_n$ uma partição de $\Omega$. Então para qualquer evento $B$, $$\mathbb{P}(B) = \sum_{i=1}^{n} \mathbb{P}(A_i \mid B) \mathbb{P}(A_i).$$

. . .

Teorema de Bayes: Seja $A_1, A_2,\ldots,A_n$ uma partição de $\Omega$ tal que $\mathbb{P}(A_i) > 0$ para cada $i$. Se $\mathbb{P}(B) > 0$, então $\forall i$ $$P(A_i \mid B) = \frac{ \mathbb{P}(B \mid A_i) \mathbb{P}(A_i) }{ \sum_{i=1}^{n} \mathbb{P}(B \mid A_i) \mathbb{P}(A_i)}$$

## Exemplo (HIV)

Suponha que temos um teste para HIV com sensibilidade ($P(+ \mid D)$) de 95% e especificidade ($P(- \mid D^c)$) de 94%. A prevalência, isto é, a probabilidade de encontrar uma pessoa entre 15 e 49 anos vivendo com HIV no Brasil, segundo dados abertos do banco mundial, é de 0.6%.

. . .

Suponha também que uma pessoa foi aleatoriamente selecionada no país, testada e o resultado foi positivo. Qual a probabilidade dela de fato estar vivendo com o HIV?

## Exemplo (HIV)

Informações: 

$\mathbb{P}(+ \mid D) = 0.95$, $\mathbb{P}(- \mid D^c) = 0.94$, $\mathbb{P}(D) = 0.006$

. . .

Queremos: $\mathbb{P}(D \mid +)$

. . .

Aplicando o teorema de Bayes temos que:
$$\mathbb{P}(D \mid +) = \frac{\mathbb{P}(+ \mid D)\mathbb{P}(D)}{\mathbb{P}(+ \mid D)\mathbb{P}(D) + \mathbb{P}(+ \mid D^c)\mathbb{P}(D^c)}$$

. . .

$$ = \frac{0.95 \times  0.006}{0.95 \times  0.006 + (1-0.94) \times  (1-0.006)} = 0.087$$

## Exemplo (HIV)

E se a pessoa fosse de uma população chave, em particular HSH, cuja prevalência de HIV é de 7.7%?

\begin{eqnarray}
\mathbb{P}(D \mid +) & = & \frac{0.95 \times  0.077}{0.95 \times  0.077 + (1-0.94) \times  (1-0.077)} \\
& = & 0.569
\end{eqnarray}


## Definições de probabilidade

